- hosts: win
  become_method: runas
  gather_facts: false
  roles:
    - { role: ad, dcpromote: true }
  tags:
    - dcpromote

- hosts: win
  become_method: runas
  gather_facts: false
  roles:
    - { role: ad, adconfig2: true }
  tags:
    - adconfig2

- hosts: win
  become_method: runas
  gather_facts: false
  vars:
     ansible_user: administrator@ADTEST07.ORG
     ansible_password: vagrant
  roles:
    - { role: ad, cert_authority: true }
  tags:
    - cert_authority

- name: change password win
  hosts: win
  become_method: runas
  gather_facts: false
  roles:
    - { role: ad, changepassword: true, passadmin: P@ssw0rd7 }
  tags:
    - changepassword

- name: windows audit
  hosts: win
  become_method: runas
  gather_facts: false
  vars:
    wintmp: c:\temp
  roles:
    - { role: ad, test: true }
  tags:
    - test
[vagrant@ansible ~/hadoop]
$^C
[vagrant@ansible ~/hadoop]
$cat ldap.yml


- name: test
  hosts: localhost ansible_connection=local
  gather_facts: false
  become: true
  any_errors_fatal: False
  roles:
    - { role: common, test: true }
  tags:
    - test

